Gitactions (#1)
* test: testing

* feat: jest conf done

* test: unit testing done

* test: my-test

* feat: github actions added

* feat: pre commit changed

* fix: yml

Co-authored-by: kunjo.lee <kunjo.lee@telusinternational.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -17,9 +17,15 @@ yarn check-format || (
 )
 
 #Check Eslint Standars
-
 yarn lint || (
     echo 'EsLint check failed 
         Make the required changes, add them and try commit again.'
+    false;
+)
+
+#Check jest
+yarn test || (
+    echo 'Jest tests check failed 
+        Pass all tests, and try commit again.'
     false;
 )
